### ISSUE TITLE
[Anon] Bug report: Dust_1947.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/dust1947#1]
**File:** Dust_1947.gstz

**BattleScribe version:** 1.15.10

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Everytime I try to load a force, it closes the app. Only with Dust 1947. All my other game lists for other game systems loads just fine.. I have already redownload the file and also each seperate faction file and it still closes the app when I try to select force..

**Comment by frankysan** [comment]
These data files require BattleScribe 2.0 or newer. On iOS, it's a new separate download, it won't be updated automatically.
