### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by koihin** [BSData/dust1947#4]
Hi there, I would like to assist with the update and maintenance of these files.

**Comment by amis92** [comment]
Hello, @koihin. Please accept the invitation in the email or on the [BSData organization webpage](https://github.com/BSData). Welcome aboard!

Don't forget to read through [Wiki pages](https://github.com/BSData/bsdata/wiki), there are some useful guides, especially [Developer Guide](https://github.com/BSData/bsdata/wiki/Developer-Guide).

wh40k team also has quite active Gitter chat room (GitHub login): [![Join the chat at https://gitter.im/BSData/wh40k](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/BSData/wh40k?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

Cheers!

**Comment by amis92** [comment]
Invitation withdrawn due to age.
